[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork
priority=10
autorestart=true

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=":1",HOME="/root",USER="root"
directory=/root
priority=20
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -listen 127.0.0.1 -rfbport 5900
priority=30
autorestart=true

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 127.0.0.1:6080 127.0.0.1:5900
priority=40
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=45
autorestart=true

[program:xray]
command=/opt/xray/xray run -config /etc/xray/config.json
priority=50
autorestart=true
stdout_logfile=/var/log/xray.log
stderr_logfile=/var/log/xray-error.log
